language: node_js
node_js:
  - 0.12
env:
  global:
    - GH_REF: github.com/vaeum/plastpolimer.git
    - secure: oeYteWT9OUfqx8UbLfevGaIrYY+cBq4Icw/jQlncG2zl2rA5BUxw8gg/xkYahW55wKfYsen42A/1tJg2+lZ2lfyvjDyWwbSORvFYLRr+os28KgWbXs/Z7oBS/lfO6D2O4Ou4/gXh/MPZOL+ZU0iTFcsaEzfGRl9COghwtHHgxxHMnx31zUi0huXUmn79yH+V/PiWKJwdw+ZezlpCawT+ZSv4hGMmAsvxnWjR8nbNmJkWH8WUva7tWwA4xYhF1LdjvB13rqLfNtPyJqm0JpvAmoi/MEeZVBPWgDinkmyiVy0Wt1R8RnjmgiHFx22KWRkOUhmYck+Fh0sbOyoTDFbp5EvJ4eV7RoiM1PtpWuJoSqs79lgBjGibs8mU5wNh4jtQ2UwK62YlekW+2X5zW0N4ufOBc91bq7yidZtzvsBFK2AnZKzDs9OOMVUkZGlEEKWDYRF+cE/+Xo2E0FWFsIiXAtymFWT+oPgwu5z2i5Ooc3aU2d0ClPkWV3tM6B/mi6INwnZ0dvsdUbZT478iF6Us91+6XGktQlsbaZ+UHLHlmXMvKtuqQwMgWEXDIVuKSpTz47m1pcvYWzHMevWtSZJBnNsVdT7/8tHLTgcR6aYfqf4kYjOjC8I8d2kjTWS+3acZyxhImSQXUUEPcPQ7yXEtlEtzWEZ4xg9OuTS63zEAZ+o=
before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - npm install
script:
  - npm run build
  - cd app
  - git init
  - 'git config user.name "Alexander Anpleenko"'
  - 'git config user.email "vaeum@yahoo.com"'
  - git add .
  - 'git commit -m "Deploy to GitHub Pages"'
  - 'git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1'
